parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"
    - "config"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/glove80.h>
    #define CONFIG_WIRELESS
    #include "misc/unicodes.dtsi"

  
  raw_binding_map:
    "&kp DQT": \"
    "&combo_dv_macro": "dv"
    "&combo_dv_macro": "dv"
    "&combo_sh_macro": "sh"
    "&combo_gt_macro": "gt"
    "&combo_rk_macro": "rk"
    "&combo_cspacebase_macro": "C Sp"
    "&combo_5spacebase_macro": "5 Sp"
    "&cool_caps": "Cool Caps"
    "&sk RC(RSHIFT)": "Ctrl Shift"
    "&sk LC(LSHIFT)": "Ctrl Shift"
    "&combo_au_macro": "au"
    "&enterer": "Enter"
    "&combo_eo_macro": "eo"
    "&base_adapt": "æ ."
    "&nums_plus": "Num Plus"
    "&num_adapt": "."
    "&num_plus_or_perma": "Num"
    "&cancel_dot": "Cancel (Dot)"
    "&cancel_tristate": Cancel
    "&cancel_backspacer": "Cancel Bspc"
    "&pulse_auto": "Pulse Auto"
    "&numnex": "Num + Nexus"
    "&bnums_perma": "Num Perma"
    "&cbd_word": "Base Dot"
    "&cd_word": "Caps Dot"
    "&minuser": "-"
    "&scr_slow": "Slow Scroll"
    "&scr_warp": "Warp Scroll"
    "&grave": "`"
    "&tilder": "~"
    "&senterer": "Shift Enterer"
    "&coolword": "Cool Caps Word"
    "&capvim": "2nd Vim Word"
    "&j_lock": "J Lock"
    "&f_lock": "F Lock"
    "&caret": "^"
    "&bpulse": "Base Pulse"
    "&sticky_w": "Sticky W"
    "&star": "*"
    "&att": "@"
    "&plus": "+"
    "&equal": "="
    "&percent": "%"
    "&bnums_plus": "Num Plus"
    "&quoter": '"'
    "&less": "<"
    "&greater": ">"
    "&qmark": "? (Enter)"
    "&exclaim": "! (Enter)"
    "&tabber": "⭾"
    "&hash": "#"
    "&bslash": "\\"
    "&undctrl": "CTRL _"
    "&amp": "&"
    "&amp": "&"
    "&pipe": "|"
    "&deleter": Deleter
    "&cdeleter": Ctrl Deleter
    "&smart_q": Q
    "&oo_ak": Ö (.)
    "&two_kps Q U": QU
    "&hold_navauto LEFT NAV_WORD": ← Auto
    "&hold_navauto RIGHT NAV_WORD": → Auto
    "&hold_navauto DOWN NAV_WORD": ↓ Auto
    "&hold_navauto UP NAV_WORD": ↑ Auto
    "&nav_gui": Nav Gui
    "&kp C_PLAY_PAUSE": ⏯
    "&kp C_NEXT": ⏭
    "&kp C_PREV": ⏮
    "&colon": ":"
    "&semi": ";"
    "&camps": "&"
    "&nav_shift": Nav Shift
    "&nav_guishift_macro": Nav Gui Shift
    "&nav_guish": Nav Gui Shift
    "&nav_guishctrl": "Nav Gui+Alt"
    "&nav_guictrl": Nav Gui Ctrl
    "&nav_alt": Nav Alt
    "&nav_ctrl": Nav Ctrl
    "&nav_ctrlshift_macro": Nav Ctrl Shift
    "&pag": Page Nav
    "&vim": Vim Nav
    "&enters": Enter
    "&escaper": Esc
    "&slash": /
    "&pcapsword": Dotted Caps Word
    "&ctrl_lock": Ctrl Lock
    "&aunav": Nav Word (au)
    "&lorshift": L (Shift)
    "&jl": J (L)
    "&eter": E LSHIFT (Enter)
    "&shift_repeat": Shift Repeat
    "&jl": J (L)
    "&eter": E LSHIFT (Enter)
    "&shift_repeat": Shift Repeat
    "&rshift_repeat": RShift Repeat
    "&to UNIC_LAYER": Unicode Layer
    "&thorn_eth": Þ / Ð
    "&scrup_warp": Scroll ▲ (Warp)
    "&scrdn_warp": Scroll ▼ (Warp)
    "&scrup_fast": Scroll ▲ (Fast)
    "&scrdn_fast": Scroll ▼ (Fast)
    "&scrup_slow": Scroll ▲ (Slow)
    "&scrdn_slow": Scroll ▼ (Slow)
    "&navigation": Nav Word
    "&nexus_auto": Nexus Auto
    "&tog UNDER_SPACE": _ space
    "&mpcaps": "Strong Caps Word"
    "&basecaps": "Caps Word"
    "&skalt": "Alt Sticky"
    "&skshift": "Shift Sticky"
    "&skgui": "Gui Sticky"
    "&skctrl": "Ctrl Sticky"
    # pretty labels for numword "go-to-layer then sticky-mod" macro keys
    "&to_then_sk NUM_WORD_MODDED LCTRL": Num Ctrl
    "&to_then_sk NUM_WORD_MODDED RCTRL": Num Ctrl
    "&to_then_sk NUM_WORD_MODDED LALT": Num Alt
    "&to_then_sk NUM_WORD_MODDED RALT": Num Alt
    "&to_then_sk NUM_WORD_MODDED LSHIFT": Num Shift
    "&to_then_sk NUM_WORD_MODDED RSHIFT": Num Shift
    "&to_then_sk NUM_WORD_MODDED LGUI": Num Gui
    "&to_then_sk NUM_WORD_MODDED RGUI": Num Gui
    "&dqt_l": '" (L)'
    "&nums_perma": Num Perma
    "&ae_dot": Æ (.)
    "&cskalt": "Alt Sticky"
    "&cskshift": "Shift Sticky"
    "&cskgui": "Gui Sticky"
    "&cskctrl": "Ctrl Sticky"
    "&cs_pgup": "CtSh Page Up"
    "&cs_pgdn": "CtSh Page Down"
    "&ctrl_w": "Ctrl W"
    "&gui_tab": "Gui Tab"
    "&sgui_tab": "GuiSh Tab"
    "&ctrl_tab": "Ctrl Tab"
    "&sctrl_tab": "CtSh Tab"
    "&sqt_nex": "' Nexus"
    "&spacebase": Space Base
    "&tabbase": Tab Base
    "&enterbase": Enter Base
    "&leftbase": ← Base
    "&rightbase": → Base
    "&downbase": ↓ Base
    "&upbase": ↑ Base
    "&sbase": S Base
    "&doller": "$"
    "&minusbase": "- Base"
    "&slashbase": "/ Base"
    "&underbase": "_ Base"
    "&minusbase_eq": "- Base (=)"
    "&num_adaptive": Num Adapt
    "&bnav": Nav
    "&cnav": Nav
    "&bnexus": Base Nexus
    "&bsymbol": Base Symbol
    "&kp TAB": Tab
    "&tabs": Tab
    "&kp ENTER": Enter
    "&fnumwordp": Num Plus
    "&kp RA(Z)": Æ
    "&kp RA(P)": Ö
    "&kp RA(D)": Ð
    "&kp RA(T)": Þ
    "&degsign": "°"
    "&key_repeat": Repeat
    "&numword_autolayer NUM_WORD": Num Word
    "&adaptive": Æ Adapt
    "&numsl": Num
    "&numsr": Num
    "&adaptive_up": ↑ (ak)
    "&ad_up": ↑ (ak)
    "&magic MAGIC BASE": Magic
    "&sl ICE": Ísl komma
    "&bspc_del": ⌫ ⌦
    "&kp BACKSPACE": ⌫
    "&kp DELETE": ⌦
    "&sl NUM_WORD": Sticky Num
    "&sl NEXUS": Nexus
    "&capsword": Caps Word
    "&mouse_hold_tap MOUSE MOUSE": Mouse
    "&scroll_speed_up": Scroll Speed ↑
    "&scroll_speed_down": Scroll Speed ↓
    "&mouse_slow": Slow
    "&mouse_fast": Fast
    "&mouse_warp": Warp
    "&mouse_fast_hold": "Fast (Hold)"
    "&page_up": PAGE ↑
    "&page_down": PAGE ↓
    "&kp CLEAR_AGAIN": Stay
    "&fnumword": Num Word
    "&fsl_num": Sticky Num
    "&fsl_num": Sticky Num
    "&kp C_MUTE": 🔇
    "&volume_down": 🔉
    "&volume_up": 🔊
    "&kp C_VOL_DN": "🔈⬇"
    "&kp C_VOL_UP": "🔊⬆"

    "&sys_reset": Reset
    "&bootloader": Boot
    "&caps_word": Caps Word

    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4
    "&bt_0": BT 1
    "&bt_1": BT 2
    "&bt_2": BT 3
    "&bt_3": BT 4

    "&kp LC(INS)": Copy
    "&kp LC(X)": Cut
    "&kp LS(INS)": Paste
    "&copy_base": Copy
    "&cut_base": Cut

    "&kp LG(LC(LEFT))": Prev Desk
    "&kp LG(LC(RIGHT))": Next Desk
    "&kp LG(LC(LS(A)))": Pin App
    "&kp LG(LC(LS(Q)))": Pin Win

    "&swapper": Next Win
    "&kp LS(TAB)": Prev Win
    "&dot_spc": Sentence
    "&num_dance": { "t": "Numword", "s": "Sticky Num" }
    "&magic_shift": { "t": Magic, "h": "Shift" }
    "&smart_mouse": Smart Mouse

    "&hml LS(LALT)TAB": Tab
    "&hm_combo_ldr": Leader
    "&hm_combo_ldrsh": Shift+Leader
    "&hm_combo_lpar": { "t": "(", "right": "<" }
    "&hm_combo_rpar": { "t": ")", "right": ">" }
    "&kp LBKT": "["
    "&kp RBKT": "]"

    "&mmv MOVE_UP": Mouse ↑
    "&mmv MOVE_DOWN": Mouse ↓
    "&mmv MOVE_LEFT": Mouse ←
    "&mmv MOVE_RIGHT": Mouse →

    "&msc SCRL_UP": Scroll ↑
    "&msc SCRL_DOWN": Scroll ↓
    "&msc SCRL_LEFT": Scroll ←
    "&msc SCRL_RIGHT": Scroll →

    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MCLK": Middle Click
    "&mkp MB4": Back Click
    "&mkp MB5": Forward Click

    # Unicode layer bindings → rendered symbols
    "&uc alien_uc": "👽"
    "&uc ufo_uc": "🛸"
    "&uc rocket_uc": "🚀"
    "&uc magic_wand_uc": "🪄"
    "&uc wizard_uc": "🧙"
    "&uc elf_uc": "🧝"
    "&uc vampire_uc": "🧛"
    "&uc zombie_uc": "🧟"
    "&uc crystal_ball_uc": "🔮"
    "&uc sparkle_uc": "✨"

    "&uc clown_uc": "🤡"
    "&uc partying_face_uc": "🥳"
    "&uc joy_uc": "😂"
    "&uc star_struck_uc": "🤩"
    "&uc heart_eyes_uc": "😍"
    "&uc exploding_head_uc": "🤯"
    "&uc smirk_uc": "😏"
    "&uc thinking_uc": "🤔"
    "&uc scream_uc": "😱"
    "&uc boom_uc": "💥"
    "&uc skull_uc": "💀"

    "&uc hear_no_evil_uc": "🙉"
    "&uc ok_hand_uc": "👌"
    "&uc brain_uc": "🧠"
    "&uc waving_hand_uc": "👋"
    "&uc fire_combo_uc": "🔥 💥"
    "&uc dagger_uc": "†"
    "&uc livelong_uc": "🖖"
    "&uc metal_uc": "🤘"
    "&uc turtle_uc": "🐢"

    "&uc yinyang_uc": "☯"
    "&uc pinched_fingers_uc": "🤌"
    "&uc euro_uc": "€"
    "&uc palm_up_hand_uc": "🫴"
    "&uc less_combo_uc": "≤ ≪"
    "&uc saluting_face_uc": "🫡"
    "&uc greater_combo_uc": "≥ ≫"
    "&uc impliesiff_uc": "⇒ ⇔"
    "&uc index_pointing_at_the_viewer_uc": "🫵"

    "&uc star_glow_uc": "🌟"
    "&uc 0x2764 0": "❤"
    "&uc broken_heart_uc": "💔"
    "&uc two_hearts_uc": "💕"
    "&uc permille_uc": "‰"
    "&uc sparkling_heart_uc": "💖"
    "&uc revolving_hearts_uc": "💞"
    "&uc tada_uc": "🎉"
    "&uc books_uc": "📚"

    "&uc warning_uc": "⚠"
    "&uc exclamation_uc": "❕ ❗"
    "&uc question_uc": "❔ ❓"
    "&uc left_uc": "←"
    "&uc right_uc": "→"
    "&uc tradecopy_uc": "™ ©"
    "&uc dice_uc": "🎲"
    "&uc bullseye_uc": "🎯"
    "&uc sob_skull_uc": "😭 💀"
    "&uc down_uc": "↓"
    "&uc up_uc": "↑"
    "&uc underage_uc": "🔞"
    "&uc no_mobile_phones_uc": "📵"
    "&uc peace_uc": "☮"

    # Direct numeric example
    "&uc fire_combo_uc": "🔥 💥"

  trans_legend: { "t": "", "type": "trans" }

  zmk_combos:
    combo_cut: { align: bottom, o: 0.15 }
    combo_ldrsh: { align: top, o: 1.35 }

    combo_lt: { hidden: true }
    combo_gt: { hidden: true }
    combo_lbrc: { hidden: true }
    combo_rbrc: { hidden: true }

  zmk_keycode_map:
    # custom mappings
    LALT: Alt
    RALT: Alt
    LCTRL: Ctrl
    RCTRL: Ctrl
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift

    BSPC: Bspc
    DEL: Del
    ESC: Esc
    RET: Enter
    SPACE: Spc
    TAB: Tab

    PG_UP: PgUp
    PG_DN: PgDn
    INS: Ins
    HOME: Home
    END: End

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    # C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$

    # defaults
    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    AT_SIGN: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    EXCLAMATION: "!"
    FSLH: /
    GRAVE: "`"
    GREATER_THAN: ">"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LEFT_BRACE: "{"
    LEFT_BRACKET: "["
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: "-"
    NON_US_BACKSLASH: \
    NON_US_BSLH: "|"
    NON_US_HASH: "#"
    NUHS: "#"
    PERCENT: "%"
    PERIOD: .
    PIPE: "|"
    PIPE2: "|"
    PLUS: +
    POUND: "#"
    PRCNT: "%"
    QMARK: "?"
    QUESTION: "?"
    RBKT: "]"
    RBRC: "}"
    RIGHT_BRACE: "}"
    RIGHT_BRACKET: "]"
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: "'"
    SLASH: /
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    TILDE2: "~"
    UNDER: _
    UNDERSCORE: _

draw_config:
  append_colon_to_layer_header: false
  dark_mode: true
  footer_text: "urob/zmk-config"
  physical_layout: glove80
